[project]
name = "telegram-account-switcher"
version = "2.0.0"
description = "Telegram Account Switcher Project!"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "cryptography==47.0.0",
    "loguru>=0.7.3",
    "nuitka==4.0.8",
    "psutil>=7.2.1",
    "pyside6>=6.11.0",
    "tgcrypto>=1.2.5",
    "watchdog>=6.0.0",
    "zstandard>=0.25.0",
]
